### ISSUE TITLE
Floor extensions in corner units (where heating coils were removed)

### ISSUE THREAD

**Issue by avinewman** [2400-Lakeview/Maintenance#5]
From 1801
![ED129C7D-B647-4FC7-9BCC-26D7DC909DDF](https://user-images.githubusercontent.com/1672833/206014305-0a111bdf-cc1f-4e69-ba24-208e1b730b14.jpeg)

**Comment by avinewman** [comment]
From 1906
![99E5C3DA-8C43-4CCD-B132-13851958B873](https://user-images.githubusercontent.com/1672833/206014549-5dd2ee3b-5890-4bf9-8c28-4148261b19ad.jpeg)

![76206A2D-164F-4B9D-8F68-5AD63359F736](https://user-images.githubusercontent.com/1672833/206014577-99d3354c-a0db-4c0c-9d62-23f32ce1f3a6.jpeg)

**Comment by avinewman** [comment]
Here are the photos again in an easily shareable link (expires in 30 days):
https://share.icloud.com/photos/03enMSptafa4WrfTr_BHhu1vA

**Comment by avinewman** [comment]
@JohnL2400 
Here are the photos again in an easily shareable link (expires in 30 days):
https://share.icloud.com/photos/03enMSptafa4WrfTr_BHhu1vA

Something nice about these photos is that you have an example here with flooring as well as carpeting.

Once you have shared this link with the person who asked for it, please press the "Close" button below.

Note, I tagged the ticket as "enhancement" and "documentation" to make them easier to find in the future.

**Comment by JohnL2400** [comment]
Thank you Avi. I will forward to the resident. John Lazarvitch2400 N. LakeviewChicago, IL. 60614On Dec 6, 2022, at 2:24 PM, Avi Newman ***@***.***> wrote:﻿
Here are the photos again in an easily shareable link (expires in 30 days):
https://share.icloud.com/photos/03enMSptafa4WrfTr_BHhu1vA
